In [1]:
import numpy as np
import pandas as pd

# Define payment methods and features
payment_methods = ["Amazon Pay UPI", "Google Pay", "PhonePe", "Credit Card", "Debit Card", "EMI", "Net Banking", "Cash on Delivery"]
num_payment_methods = len(payment_methods)

# User types in cyclic order
user_types = ["cashback_oriented", "cost_oriented", "history_oriented"]

# Function to generate user data
def generate_user_data(num_users):
    data = []
    user_payment_history = {user_id: {method: 0 for method in payment_methods} for user_id in range(1, num_users + 1)}
    payment_success_rates = {method: {"success": 0, "total": 0} for method in payment_methods}

    for user_id in range(1, num_users + 1):
        user_type_index = 0  # Start with the first user type
        num_products = np.random.randint(5, 51)
        for product_id in range(1, num_products ):  # Assuming each user orders 10 products
            price = np.random.randint(100, 10000)  # Random price between 100 and 10000
            payment_options = []

            for method in payment_methods:
                cost = np.random.uniform(0.01, 0.05) * price  # Cost as percentage of the product price
                cashback = np.random.uniform(0.01, 0.10) * price  # Cashback as percentage of the product price

                # Calculate current success rate based on past transactions
                success = payment_success_rates[method]["success"]
                total = payment_success_rates[method]["total"]
                success_rate = (success / total) if total > 0 else np.random.uniform(0.80, 0.99)

                user_history = min(user_payment_history[user_id][method], 10)  # User history (how many times used in recent transactions)

                payment_options.append({
                    "method": method,
                    "cost": cost,
                    "cashback": cashback,
                    "success_rate": success_rate,
                    "user_history": user_history
                })

            user_type = user_types[user_type_index % len(user_types)]  # Determine the current user type in cyclic order

            # Determine the best payment method based on user type
            if user_type == "cashback_oriented":
                best_method = max(payment_options, key=lambda x: x["cashback"])["method"]
            elif user_type == "history_oriented":
                best_method = max(payment_options, key=lambda x: x["user_history"])["method"]
            elif user_type == "cost_oriented":
                best_method = min(payment_options, key=lambda x: x["cost"])["method"]

            for option in payment_options:
                label = 1 if option["method"] == best_method else 0
                data.append([user_id, product_id, user_type, option["method"], price, option["cost"], option["cashback"], option["success_rate"], option["user_history"], label])

            # Update user payment history and success rates after generating data for each product
            for option in payment_options:
                if option["method"] == best_method:
                    user_payment_history[user_id][option["method"]] += 1
                    if np.random.rand() > 0.05:  # Assuming a 95% success rate for each transaction
                        payment_success_rates[option["method"]]["success"] += 1
                    payment_success_rates[option["method"]]["total"] += 1

            user_type_index += 1  # Move to the next user type for the next product

    return data

# Number of users
num_users = 100

# Generate data for users
combined_data = generate_user_data(num_users)

# Define columns
columns = ["user_id", "product_id", "user_type", "payment_method", "price", "cost", "cashback", "success_rate", "user_history", "label"]

# Create DataFrame
df = pd.DataFrame(combined_data, columns=columns)

# Save to CSV
df.to_csv("user_payment_data.csv", index=False)


print(df.head(30))

    user_id  product_id          user_type    payment_method  price  \
0         1           1  cashback_oriented    Amazon Pay UPI   9722
1         1           1  cashback_oriented        Google Pay   9722
2         1           1  cashback_oriented           PhonePe   9722
3         1           1  cashback_oriented       Credit Card   9722
4         1           1  cashback_oriented        Debit Card   9722
5         1           1  cashback_oriented               EMI   9722
6         1           1  cashback_oriented       Net Banking   9722
7         1           1  cashback_oriented  Cash on Delivery   9722
8         1           2      cost_oriented    Amazon Pay UPI   3353
9         1           2      cost_oriented        Google Pay   3353
10        1           2      cost_oriented           PhonePe   3353
11        1           2      cost_oriented       Credit Card   3353
12        1           2      cost_oriented        Debit Card   3353
13        1           2      cost_oriented               EMI   3353
14        1           2      cost_oriented       Net Banking   3353
15        1           2      cost_oriented  Cash on Delivery   3353
16        1           3   history_oriented    Amazon Pay UPI   3056
17        1           3   history_oriented        Google Pay   3056
18        1           3   history_oriented           PhonePe   3056
19        1           3   history_oriented       Credit Card   3056
20        1           3   history_oriented        Debit Card   3056
21        1           3   history_oriented               EMI   3056
22        1           3   history_oriented       Net Banking   3056
23        1           3   history_oriented  Cash on Delivery   3056
24        1           4  cashback_oriented    Amazon Pay UPI   5492
25        1           4  cashback_oriented        Google Pay   5492
26        1           4  cashback_oriented           PhonePe   5492
27        1           4  cashback_oriented       Credit Card   5492
28        1           4  cashback_oriented        Debit Card   5492
29        1           4  cashback_oriented               EMI   5492

          cost    cashback  success_rate  user_history  label
0   453.139588  379.088099      0.988085             0      0
1   278.893667  363.658093      0.814054             0      0
2   413.884934  189.373006      0.867830             0      0
3   170.663767  476.919014      0.809076             0      0
4   417.602308  210.423615      0.886429             0      0
5   396.546189  194.060436      0.969589             0      0
6   251.747103  784.255132      0.891198             0      1
7   173.105501  683.811172      0.877745             0      0
8    46.816380  121.701221      0.984371             0      0
9   128.426112  300.032614      0.916473             0      0
10   90.614877   96.451450      0.956003             0      0
11  129.518099  124.683738      0.969823             0      0
12   34.457061  201.124395      0.852005             0      1
13   47.008712  161.673783      0.868925             0      0
14   65.188776  267.241989      1.000000             1      0
15   60.503077  253.755066      0.801994             0      0
16  119.538624  274.715926      0.808638             0      0
17  136.421965  157.539700      0.800549             0      0
18   71.443748  216.623705      0.842709             0      0
19   80.550561  174.322503      0.955331             0      0
20  103.786675  243.626677      1.000000             1      1
21   90.911386  225.203430      0.927369             0      0
22   43.135736  217.325063      1.000000             1      0
23   62.813490  119.688675      0.903175             0      0
24   57.270340  196.270875      0.918591             0      0
25  157.694052  431.704984      0.969132             0      0
26  232.018405  493.926318      0.855878             0      1
27  132.168078  481.536325      0.816351             0      0
28  262.437297   62.402683      1.000000             2      0
29  180.231953  311.979637      0.951450             0      0

In [2]:
df[0 : 20]

,user_id,product_id,user_type,payment_method,price,cost,cashback,success_rate,user_history,label
0,1,1,cashback_oriented,Amazon Pay UPI,9722,453.139588,379.088099,0.988085,0,0
1,1,1,cashback_oriented,Google Pay,9722,278.893667,363.658093,0.814054,0,0
2,1,1,cashback_oriented,PhonePe,9722,413.884934,189.373006,0.867830,0,0
3,1,1,cashback_oriented,Credit Card,9722,170.663767,476.919014,0.809076,0,0
4,1,1,cashback_oriented,Debit Card,9722,417.602308,210.423615,0.886429,0,0
5,1,1,cashback_oriented,EMI,9722,396.546189,194.060436,0.969589,0,0
6,1,1,cashback_oriented,Net Banking,9722,251.747103,784.255132,0.891198,0,1
7,1,1,cashback_oriented,Cash on Delivery,9722,173.105501,683.811172,0.877745,0,0
8,1,2,cost_oriented,Amazon Pay UPI,3353,46.816380,121.701221,0.984371,0,0
9,1,2,cost_oriented,Google Pay,3353,128.426112,300.032614,0.916473,0,0
10,1,2,cost_oriented,PhonePe,3353,90.614877,96.451450,0.956003,0,0
11,1,2,cost_oriented,Credit Card,3353,129.518099,124.683738,0.969823,0,0
12,1,2,cost_oriented,Debit Card,3353,34.457061,201.124395,0.852005,0,1
13,1,2,cost_oriented,EMI,3353,47.008712,161.673783,0.868925,0,0
14,1,2,cost_oriented,Net Banking,3353,65.188776,267.241989,1.000000,1,0
15,1,2,cost_oriented,Cash on Delivery,3353,60.503077,253.755066,0.801994,0,0
16,1,3,history_oriented,Amazon Pay UPI,3056,119.538624,274.715926,0.808638,0,0
17,1,3,history_oriented,Google Pay,3056,136.421965,157.539700,0.800549,0,0
18,1,3,history_oriented,PhonePe,3056,71.443748,216.623705,0.842709,0,0
19,1,3,history_oriented,Credit Card,3056,80.550561,174.322503,0.955331,0,0

In [3]:
df.shape

(20664, 10)